### ISSUE TITLE
ERROR IN parseAndroidManifext

### ISSUE THREAD

**Issue by tejas619** [sensepost/kwetza#2]
When I am trying to run the module on a random apk, i get this error.
Can you help me fixing this?

**Comment by brompwnie** [comment]
We are investigating the issue and it looks like that this error occurs when apktool is called from Kwetza and the paths that Kwetza is looking for, are not there. This occurs on Kali and some OS's due to apktool no placing the decompiled sources into Kwetza's working directory. A quick fix would to see how apktool executes on your OS and amend Kwetza.py accordingly. We are working on a fix to solve this portability issue.

**Comment by nmweizi** [comment]
当decompile目录有小数点时，targetFolder赋值错误，将小数点后面部分丢了。
类似这样的，asf.3.5.apk

**Comment by brompwnie** [comment]
This has been fixed with the latest commit.
